apiVersion: yago.aerdei.com/v1alpha1
kind: Yago
metadata:
  name: example-yago
spec:
  # Add fields here
  repository: https://github.com/aerdei/yaml-repo-test
  branchReference: "master"
  forceUpdate: true
